name: DeployToSurge
env:
  PUBLISH_DIR: bin/Release/netstandard2.1/publish/wwwroot
  # Include subfolders if needed

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build :latest
      run: docker build --build-arg surge_token=${{ secrets.surge_token }} -t meirkr/whatsapp_phone_connect:latest .
